services:
  # Unified Web Service (Hosts both Frontend UI & Express Backend API)
  - type: web
    name: infinity-run-marathon
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_DEFAULT_EMAIL
        value: admin@infinityrun.com
      - key: ADMIN_DEFAULT_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false


